version: '3.8'
services:
  server:
    image: node:20-alpine
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/src/app
      - ./backend.sh:/init.sh
    working_dir: /usr/src/app
    command: sh -c "chmod +x /init.sh && /init.sh"
    env_file:
      - ./backend/.env
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: myproductsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env
    command: sh -c "npm install && npm run start"
    ports:
      - "3000:3000"
