version: "3.8"
services:
  server:
    image: node:20-alpine
    volumes:
      - ./backend:/usr/src/app
      - ./backend.sh:/init.sh
    working_dir: /usr/src/app
    command: sh -c "chmod +x /init.sh && /init.sh"
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: myproductsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    env_file:
      - ./.env
    command: sh -c "npm install && npm run start"
  adminer:
    image: adminer
    volumes:
      - ./nginx/logs:/var/log/nginx
  nginx:
    image: nginx:latest
    ports:
      - "${SERVER_PORT}:80"
      - "${SERVER_PORT_HTTPS}:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./nginx/logs:/var/log/nginx
    env_file:
      - ./.env
    depends_on:
      - frontend
      - server
      - adminer
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  fail2ban:
    image: crazymax/fail2ban:latest
    volumes:
      - ./fail2ban/data:/data
      - ./nginx/logs:/var/log/nginx:ro    # Monte les logs Nginx en lecture seule
      - ./adminer/logs:/var/log/adminer:ro # Monte les logs Adminer en lecture seule
    environment:
      - TZ=Europe/Paris
    cap_add:
      - NET_ADMIN
  samba:
    build: ./img/samba
    volumes:
      - ./storage:/srv/samba/share
      - ./samba.sh:/init.sh:ro
    command: sh -c "chmod +x /init.sh && /init.sh"
    env_file:
      - ./.env
    ports:
      - "445:445/tcp"
