version: "3.8"

services:
  db:
    image: postgres:13
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myproductsdb

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "5001:5000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db-data:
