version: '3.8'
services:
  server:
    image: node:20-alpine
    volumes:
      - ./backend:/usr/src/app
      - ./backend.sh:/init.sh
    working_dir: /usr/src/app
    command: sh -c "chmod +x /init.sh && /init.sh"
    env_file:
      - ./backend/.env
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: myproductsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env
    command: sh -c "npm install && npm run start"
  adminer:
    image: adminer
  nginx:
    image: nginx:latest
    ports:
      - "5173:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - server
      - adminer
